apiVersion: apps/v1
kind: Deployment
metadata:
  name: postprocess
  labels:
    app: postprocess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postprocess
  template:
    metadata:
      labels:
        app: postprocess
    spec:
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: pvc-nfs
      - name: emptydir
        emptyDir: {}
      containers:
      - name: postprocess
        image: luneberry07/postprocess
        env:
        - name: MONGODB_IP
          value: '129.254.202.249'
        - name: MONGODB_PORT
          value: '27017'
        - name: MOUNT_PATH
          value: '/mnt/nfs_share/'
        - name: LOG_FILE
          value: 'postprocess.log'
        volumeMounts:
        - name: www
          mountPath: /mnt/nfs_share
        - name: emptydir
          mountPath: /app/htdocs
        ports:
        - containerPort: 80
