apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: preprocess2
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 5000
    nodePort: 30005
