apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocess2
  labels:
    app: preprocess2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preprocess2
  template:
    metadata:
      labels:
        app: preprocess2
    spec:
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: pvc-nfs
      - name: emptydir
        emptyDir: {}
      containers:
      - name: preprocess
        image: luneberry07/preprocess_v2
        env:
        - name: MONGODB_IP
          value: '101.79.4.10'
        - name: MONGODB_PORT
          value: '12002'
        - name: MOUNT_PATH
          value: '/mnt/nfs_share'
        - name: LOG_FILE
          value: 'preprocess.log'
        - name: MONGODB_ID
          value: 'gedge'
        - name: MONGODB_PW
          value: '7W4qsKuUBXywAeA'
        volumeMounts:
        - name: www
          mountPath: /app/static
        - name: emptydir
          mountPath: /app/htdocs
        ports:
        - containerPort: 80
